- cbr-rule-module/main.tf
This check should be `OR` not `AND` If any of these are null the length check will always throw an error because it is being run on a null object. 
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> fix: fix bug in null check logic

- .gitignore
- cbr-rule-module/main.tf
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/88
This is the fix, I have manually validated the context block in the UI, so I am confident the other blocks now work as expected. I will do a follow-up PR with unit tests that will cover the validation of all these blocks. The examples need to be updated too.
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.
The commit message determines whether …
> Bug fix Dynamic blocks not iterating

- .github/settings.yml
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
If the CI pipeline doesn't run when you …
> Add more topics

- cbr-service-profile/variables.tf
Updated latest list of supported services for both target and service reference.
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is …
> feat: updated latest list of supported services

- README.md
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> docs: fix link in README.md

- examples/fscloud/main.tf
Utilize key protect module in CBR fs cloud example 
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> docs: leverage existing key protect module in the fscloud example

- examples/fscloud/main.tf
- examples/fscloud/variables.tf
- modules/fscloud/README.md
- modules/fscloud/main.tf
- modules/fscloud/variables.tf
Added pre-wired rule for AT -> COS
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> feat: fscloud added pre-wired rule for AT -> COS

- modules/fscloud/variables.tf
Update the ser-ref list in fscloud profile.
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> refactor: updated the service ref list

- .github/settings.yml
> ci: add supported and graduated topic

- README.md
Add info about the cache and TTL. 
fixes https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/291
```
/run pipeline
```
> add TTL info

- README.md
- modules/cbr-rule-module/README.md
- modules/cbr-rule-module/version.tf
- modules/cbr-service-profile/README.md
- modules/cbr-service-profile/version.tf
- modules/cbr-zone-module/README.md
- modules/cbr-zone-module/version.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- version.tf
Update version constraints
https://github.ibm.com/GoldenEye/issues/issues/4915
```
/run pipeline
```
> chore: update version constraints

- examples/multi-resource-rule/main.tf
Update a reference to this module in the tests to be a local lookup rather than a potentially old version from the terraform module registry.
This is an example update, not part of the main module, so no release is required.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub …
> Replace reference to registry with local lookup

- tests/go.mod
- tests/go.sum
- tests/pr_test.go
Update the FSCloud test to run in schematics workspace
https://github.ibm.com/GoldenEye/issues/issues/7984
```
/run pipeline
```
> test: update fscloud test

- examples/fscloud/main.tf
Fixed schmatics endpoint for KP.
[Git Issue](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/456)
```
/run pipeline
```
> fix: fixed schmatics endpoint for KP

- README.md
- examples/fscloud/version.tf
- examples/multi-resource-rule/version.tf
- examples/multi-service-profile/version.tf
- examples/multizone-rule/version.tf
- examples/zone/version.tf
- modules/cbr-rule-module/README.md
- modules/cbr-rule-module/version.tf
- modules/cbr-service-profile/README.md
- modules/cbr-service-profile/version.tf
- modules/cbr-zone-module/README.md
- modules/cbr-zone-module/version.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- version.tf
Updated required ibm provider version to >= 1.65.0.
[Github issue](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/466).
```
/run pipeline
```
> fix: update required ibm provider version to >= 1.65.0

- modules/fscloud/main.tf
-  made changes in `global_deny_target_service_details` to allow consumer customization.
- Issue Reference: [Issue-483](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/483)
```
/run pipeline
```
- Use the **Squash and …
> fix: allow consumer customizations

- examples/fscloud/README.md
> docs: updated fscloud example readme

- examples/fscloud/main.tf
Updated the FScloud example so that it should be runable by any consumer on a vanilla paygo account.
[Git Issue](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/516)
```
/run pipeline
```
- Use the **Squash and merge** …
> tests: updated fscloud example to use correct zone for server-protect

- README.md
- examples/fscloud/version.tf
- examples/multi-resource-rule/version.tf
- examples/multi-service-profile/version.tf
- examples/multizone-rule/version.tf
- examples/update-existing-zone-addresses/version.tf
- examples/zone/version.tf
- modules/cbr-rule-module/README.md
- modules/cbr-rule-module/version.tf
- modules/cbr-service-profile/README.md
- modules/cbr-service-profile/version.tf
- modules/cbr-zone-module/README.md
- modules/cbr-zone-module/version.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- version.tf
Updated provider version as a fix for `Provider produced inconsistent result after apply` error in CBR zones
[Git Issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5590)
```
/run pipeline
```
- Use the **Squash and merge** …
> fix: updated provider version

- modules/fscloud/main.tf
This PR integrates cloud logs into the fscloud module
[Git Issue](https://github.ibm.com/GoldenEye/issues/issues/11552)
Add cloud logs as one of the target service in fscloud module
```
/run pipeline
```
- Use the **Squash and merge** …
> feat : Added cloud logs

- README.md
- version.tf
Missed adding for fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6269 in root module.
```
/run pipeline
```
> fix(deps): bump to ibm provider 1.79.0 in root
